# Generated by Django 6.0.5 on 2026-05-25 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_number', models.IntegerField()),
                ('heat_status', models.CharField(choices=[('not_swam', 'Not Swam'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_swam', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heats', to='events.eventdetail')),
            ],
            options={
                'ordering': ['heat_number'],
                'unique_together': {('event', 'heat_number')},
            },
        ),
        migrations.CreateModel(
            name='HeatResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_time', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('swam', 'Swam'), ('dns', 'Did Not Swim'), ('dsq', 'Disqualified')], default='swam', max_length=10)),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='heats.heatlist')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('heat', 'swimmer')},
            },
        ),
        migrations.CreateModel(
            name='HeatSwimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane_number', models.IntegerField()),
                ('seed_time', models.DurationField(blank=True, null=True)),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimmers', to='heats.heatlist')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lane_number'],
                'unique_together': {('heat', 'lane_number'), ('heat', 'swimmer')},
            },
        ),
    ]
