# Generated by Django 6.0.5 on 2026-06-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatresult',
            name='status',
            field=models.CharField(choices=[('swam', 'Swam'), ('DNS', 'Did Not Start'), ('DQ', 'Disqualified'), ('DNF', 'Did Not Finish'), ('NP', 'Not Participating')], default='swam', max_length=10),
        ),
    ]
