# Generated by Django 6.0.5 on 2026-06-06 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_organizers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appuser',
            name='association_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='association_type',
            field=models.CharField(blank=True, choices=[('district', 'District'), ('state', 'State'), ('national', 'National'), ('club', 'Club')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='contact_information',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='organizer_document',
            field=models.FileField(blank=True, null=True, upload_to='organizer_documents/'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='organizer_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
