# Generated by Django 6.0.5 on 2026-06-08 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_districtmaster_association'),
        ('users', '0003_appuser_approved_at_appuser_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='masters.association'),
        ),
    ]
