# Generated by Django 6.0.5 on 2026-06-08 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_districtmaster_association'),
        ('users', '0004_appuser_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='district_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='masters.districtmaster'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='state_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='masters.statemaster'),
        ),
    ]
