# Generated by Django 6.0.5 on 2026-06-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appuser_district_master_appuser_state_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='current_level',
            field=models.CharField(choices=[('DISTRICT', 'District'), ('STATE', 'State'), ('NATIONAL', 'National')], default='DISTRICT', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='highest_level_reached',
            field=models.CharField(choices=[('DISTRICT', 'District'), ('STATE', 'State'), ('NATIONAL', 'National')], default='DISTRICT', max_length=20),
        ),
    ]
