# Generated by Django 6.0.5 on 2026-06-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_appuser_email_verified_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email_verification_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
