# Generated by Django 6.0.5 on 2026-06-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_appuser_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='coach_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='organizer_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
