# Generated by Django 6.0.5 on 2026-05-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_m', models.IntegerField()),
                ('stroke', models.CharField(max_length=50)),
                ('is_relay', models.BooleanField(default=False)),
                ('is_marathon', models.BooleanField(default=False)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meets.agegroup')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meets.gendercategory')),
            ],
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meets.meet')),
                ('event_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventlist')),
            ],
        ),
    ]
