# Generated by Django 6.0.5 on 2026-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlist',
            name='is_junior',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='is_senior',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventlist',
            name='is_sub_junior',
            field=models.BooleanField(default=True),
        ),
    ]
