# Generated by Django 6.0.5 on 2026-06-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_districtmaster_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='association_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
