# Generated by Django 6.0.5 on 2026-06-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_association_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='association_type',
            field=models.CharField(choices=[('NATIONAL', 'National'), ('STATE', 'State'), ('DISTRICT', 'District')], max_length=50),
        ),
        migrations.AlterField(
            model_name='association',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='districtmaster',
            name='district_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
