# Generated by Django 6.0.5 on 2026-06-08 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_districtmaster_association'),
        ('meets', '0002_meet_results_published_alter_meet_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meets', to='masters.association'),
        ),
    ]
