# Generated by Django 6.0.5 on 2026-06-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0003_meet_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='meet_type',
            field=models.CharField(choices=[('CHAMPIONSHIP', 'Championship'), ('INVITATIONAL', 'Invitational'), ('TRIAL', 'Trial'), ('SELECTION', 'Selection'), ('OPEN', 'Open')], default='CHAMPIONSHIP', max_length=20),
        ),
    ]
