# Generated by Django 6.0.5 on 2026-06-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0004_meet_meet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='qualifying_position',
            field=models.PositiveIntegerField(blank=True, help_text='Top N swimmers qualify to the next level', null=True),
        ),
    ]
