# Generated by Django 6.0.5 on 2026-06-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0005_meet_qualifying_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='qualification_method',
            field=models.CharField(choices=[('POSITION', 'Position'), ('TIME', 'Time'), ('MEDAL', 'Medal'), ('POINTS', 'Points')], default='POSITION', max_length=20),
        ),
    ]
