# Generated by Django 6.0.5 on 2026-06-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0006_meet_qualification_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='qualifying_medals',
            field=models.CharField(blank=True, help_text='Comma separated medals allowed to qualify', max_length=50),
        ),
        migrations.AddField(
            model_name='meet',
            name='qualifying_points',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum championship points required', null=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='qualifying_time_standard',
            field=models.DurationField(blank=True, help_text='Minimum time standard required for qualification', null=True),
        ),
    ]
