# Generated by Django 6.0.5 on 2026-06-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0007_meet_qualifying_medals_meet_qualifying_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='max_events_per_swimmer',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
