# Generated by Django 6.0.5 on 2026-05-25 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('meets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_time', models.DurationField(blank=True, null=True)),
                ('new_time', models.DurationField()),
                ('record_date', models.DateField(auto_now_add=True)),
                ('event_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventlist')),
                ('meet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meets.meet')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to=settings.AUTH_USER_MODEL)),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='championships.recordtype')),
            ],
        ),
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('placement', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventdetail')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meets.meet')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='championships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('swimmer', 'event', 'meet')},
            },
        ),
        migrations.CreateModel(
            name='ChampionshipPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meets.meet')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='championship_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meet', 'swimmer')},
            },
        ),
    ]
