# Generated by Django 6.0.5 on 2026-06-15 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0001_initial'),
        ('events', '0002_eventlist_is_junior_eventlist_is_senior_and_more'),
        ('meets', '0008_meet_max_events_per_swimmer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified_from', models.CharField(choices=[('DISTRICT', 'District'), ('STATE', 'State'), ('NATIONAL', 'National')], max_length=20)),
                ('qualified_to', models.CharField(choices=[('DISTRICT', 'District'), ('STATE', 'State'), ('NATIONAL', 'National')], max_length=20)),
                ('rank', models.PositiveIntegerField()),
                ('qualification_time', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventdetail')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meets.meet')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('swimmer', 'event', 'qualified_to')},
            },
        ),
    ]
