# Generated by Django 6.0.5 on 2026-05-25 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('meets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_time', models.DurationField(blank=True, help_text='Swimmer best time for seeding heats', null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_back', models.BooleanField(default=False)),
                ('recall', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventdetail')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='meets.meet')),
                ('nominated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominations', to=settings.AUTH_USER_MODEL)),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('meet', 'swimmer', 'event')},
            },
        ),
        migrations.CreateModel(
            name='SwimmerBestTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_time', models.DurationField()),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('event_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventlist')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_times', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('swimmer', 'event_list')},
            },
        ),
    ]
