# Generated by Django 6.0.5 on 2026-06-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0003_meet_association'),
        ('registrations', '0002_registration_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='qualification_source_meet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualified_registrations', to='meets.meet'),
        ),
        migrations.AddField(
            model_name='registration',
            name='qualification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='qualification_type',
            field=models.CharField(blank=True, choices=[('DISTRICT_TO_STATE', 'District to State'), ('STATE_TO_NATIONAL', 'State to National')], max_length=30, null=True),
        ),
    ]
