# Generated by Django 6.0.5 on 2026-06-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_registration_approved_at_registration_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='qualification_medal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='qualification_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='qualification_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='qualified_for_next_level',
            field=models.BooleanField(default=False),
        ),
    ]
