# Generated by Django 6.0.5 on 2026-06-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_registration_qualification_medal_and_more'),
        ('results', '0002_finalresult_medal'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='qualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='qualified_by_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='results.finalresult'),
        ),
    ]
